name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          AGILITY_TEST_GUID: ${{ secrets.AGILITY_TEST_GUID }}
          AGILITY_TEST_API_KEY_FETCH: ${{ secrets.AGILITY_TEST_API_KEY_FETCH }}
          AGILITY_TEST_API_KEY_PREVIEW: ${{ secrets.AGILITY_TEST_API_KEY_PREVIEW }}
          AGILITY_TEST_BASE_URL: ${{ secrets.AGILITY_TEST_BASE_URL }}
        run: npm test
